GET http://localhost:3000/posts 
Authorization: Bearer eyJhbGciOiJQUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoibGFsYSIsImlhdCI6MTYzMjQ0Njk2NiwiZXhwIjoxNjMyNDQ3MjY2fQ.MUqthJoVYapeXSLlSBK_jGXaKtC85zpNvqIYS-IrXY3EkXXiVEypwBce5EU2DHTVdijy92VD3PrM2EhdQUjt8deGQwjiNmVwShRDzYZhOKUsbtrQ5nacn1EyfoYAqvLfvzVUT2R1TM1vhkyn-JdWxiQM5D93EWc5iSaSVv3nmJ8CtF8cTOI30-xD0beVDAtx0nndKhqoJG7GPkwHdzEpWvBOE2OZg22THnPmC0TC7mMjr16Jli42pfO-9js73fJzKNtCaDbunuDztEAf-yTKXNTcTk3oD-4faemRvPDB2lwL0VPOszs4dlpT5UnHo6Y6EVssWd10cpcIQXkzPMxomg
###

DELETE http://localhost:4000/logout 
Content-Type: application/json

{
    "token": "eyJhbGciOiJQUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoibGFsYSIsImlhdCI6MTYzMjQ0Njk2NiwiZXhwIjoxNjMyNDQ3MjY2fQ.UuqHJuJzCOpe8OeGBMdXLfUSuKHWQnQDaOfLOlScfhebYOySQmtj7LoHWcM7LCLtPwJ63q5m8MxC72XBkolwiQCAWRm2f1YY_AJx14Kh6Xd8ms3T_JNOaKa30TSxA-DlIsJDQgRVhdEF10QkK_wLRZOWB1i2lOtau1P7X2lrO-ZXH6Ileer7RHfe0XkLVseUlRrJYmW7LqfotutQOtG20o1y16sKrj9VfHsCU0I34YinnGJRlTpJ7OLvsQXDZmf5K663Ad-sznGk3W3VD3yKZTfNy5bLfpjEA7HGvlnANkoHVKCgcf6l09YXoK9FXUt2o5OqYCZFf4SM5ORshgJgFQ"
}
###
POST http://localhost:4000/token 
#ada masalah dalam generate access token baru menggunakan refresh token.
#TypeError: Cannot read property 'name' of undefined
#saya sendiri juga bingung gimana konsep pengambilan namenya dari server lain.
Content-Type: application/json

{
    "token": "eyJhbGciOiJQUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoibGFsYSIsImlhdCI6MTYzMjQ0Njk2NiwiZXhwIjoxNjMyNDQ3MjY2fQ.UuqHJuJzCOpe8OeGBMdXLfUSuKHWQnQDaOfLOlScfhebYOySQmtj7LoHWcM7LCLtPwJ63q5m8MxC72XBkolwiQCAWRm2f1YY_AJx14Kh6Xd8ms3T_JNOaKa30TSxA-DlIsJDQgRVhdEF10QkK_wLRZOWB1i2lOtau1P7X2lrO-ZXH6Ileer7RHfe0XkLVseUlRrJYmW7LqfotutQOtG20o1y16sKrj9VfHsCU0I34YinnGJRlTpJ7OLvsQXDZmf5K663Ad-sznGk3W3VD3yKZTfNy5bLfpjEA7HGvlnANkoHVKCgcf6l09YXoK9FXUt2o5OqYCZFf4SM5ORshgJgFQ"
}

###
POST  http://localhost:4000/login 
Content-Type: application/json

{
    "username": "lala"
}
 
#jika terjadi masalah mungkin di server.js nya belum manggil dotenv