GET http://localhost:3000/posts 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoibGlsaSIsImlhdCI6MTYzMTg3MTU1NSwiZXhwIjoxNjMxODcyMTU1fQ.J7G97ATplwpdCmFFlGBxBaAdQ_P5AnFFQmI9HLYA6Rg
###


POST  http://localhost:3000/login 
Content-Type: application/json

{
    "username": "lala"
}
 
#jika terjadi masalah mungkin di server.js nya belum manggil dotenv