GET http://localhost:3000/posts 
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1cm46ZXhhbXBsZTpjbGFpbSI6dHJ1ZSwiaWF0IjoxNjM1NTExMTgwLCJpc3MiOiJ1cm46ZXhhbXBsZTppc3N1ZXIiLCJhdWQiOiJ1cm46ZXhhbXBsZTphdWRpZW5jZSIsImV4cCI6MTYzNTUxODM4MH0.271EK7xjXgujGY35SOiANqFCwMMsnaUNljuEqsW4GuE
Content-Type: application/json

{
    "secret": "eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoibGFsYSIsImlhdCI6MTYzMjg5Mzg5MSwiZXhwIjoxNjMyODk0MTkxfQ.eBdP5VG6RzZT1fzBm3NcYJiUomVol40UKhiddUjpuxjLOfl6xcNHS9XJ2Ni4sHpXKQjzSXY7HgwEsoBmPNF2-OVm7mLGn8VAddOCxkkDL7DwRrIfQX5q1TU7NYObQXow0MtlWgD8bDcxwp2nWd8cxlkKs3V5sNgCTsFi97lyVKFrwYav_z6otpF3hn9VAb0d5KR4nDK8Aszj1wW2kGXVQ6NAsVakYO30SV-DOE3kZMvjrgvek0vv0gZMjCi_5QcdWb5vgKxZ1aidkHCT6W6_CJv-K5_F9wlTIAsONNTT_XgApkP5m97XV7mYxPW0m7N2YJHksWb04DccHvGtCOS6NA"
}
###

DELETE http://localhost:4000/logout 
Content-Type: application/json

{
    "token": "eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoibGFsYSIsImlhdCI6MTYzMjg5Mzg5MSwiZXhwIjoxNjMyODk0MTkxfQ.eBdP5VG6RzZT1fzBm3NcYJiUomVol40UKhiddUjpuxjLOfl6xcNHS9XJ2Ni4sHpXKQjzSXY7HgwEsoBmPNF2-OVm7mLGn8VAddOCxkkDL7DwRrIfQX5q1TU7NYObQXow0MtlWgD8bDcxwp2nWd8cxlkKs3V5sNgCTsFi97lyVKFrwYav_z6otpF3hn9VAb0d5KR4nDK8Aszj1wW2kGXVQ6NAsVakYO30SV-DOE3kZMvjrgvek0vv0gZMjCi_5QcdWb5vgKxZ1aidkHCT6W6_CJv-K5_F9wlTIAsONNTT_XgApkP5m97XV7mYxPW0m7N2YJHksWb04DccHvGtCOS6NA"
}
###
POST http://localhost:4000/token 
#ada masalah dalam generate access token baru menggunakan refresh token.
#TypeError: Cannot read property 'name' of undefined
#saya sendiri juga bingung gimana konsep pengambilan namenya dari server lain.
Content-Type: application/json

{
    "token": "eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoibGFsYSIsImlhdCI6MTYzMjg5Mzg5MSwiZXhwIjoxNjMyODk0MTkxfQ.eBdP5VG6RzZT1fzBm3NcYJiUomVol40UKhiddUjpuxjLOfl6xcNHS9XJ2Ni4sHpXKQjzSXY7HgwEsoBmPNF2-OVm7mLGn8VAddOCxkkDL7DwRrIfQX5q1TU7NYObQXow0MtlWgD8bDcxwp2nWd8cxlkKs3V5sNgCTsFi97lyVKFrwYav_z6otpF3hn9VAb0d5KR4nDK8Aszj1wW2kGXVQ6NAsVakYO30SV-DOE3kZMvjrgvek0vv0gZMjCi_5QcdWb5vgKxZ1aidkHCT6W6_CJv-K5_F9wlTIAsONNTT_XgApkP5m97XV7mYxPW0m7N2YJHksWb04DccHvGtCOS6NA"
}

###
POST  http://localhost:4000/login 
Content-Type: application/json

{
    "username": "lala"
}
 
#jika terjadi masalah mungkin di server.js nya belum manggil dotenv