GET http://localhost:3000/posts 
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.ewogICJuYW1lIjogImxvbG8iLAogICJpYXQiOiAxNjMyMzgwNDk4LAogICJleHAiOiAxNjMyMzgwNzk4Cn0=.K1reXFEZV6pWjYegLzYqZF2G5g4prA49hvGskFwzhF2R7Qguwm0eTByCYRbb4AX3uf5tQBty8mFez_dNJs5njMcCyIylc60KjeQdk2ZeHtdFLnPG75hXalUiDrbvHb3Qx3x5EaXL-Gds3SoIKBzIdymfm54k3EsFQML952gEARRbB6W5CZXmnZVcXVkRqOu97RyEIGXV3IwcKJJ3x_e6M-9V-IUHTs2Yw6ESJ_jV85DycnbABacUP3MuNuNSX6uymd2tkDfNnkIdquRu0zFbRLtKqwczzg5IraFgihvPamevb5iJtRrVrJHtEoLGQb12z_tXFwjRlyqKDgpBqFsdqg
###

DELETE http://localhost:4000/logout 
Content-Type: application/json

{
    "token": "eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoibGFsYSIsImlhdCI6MTYzMjg5Mzg5MSwiZXhwIjoxNjMyODk0MTkxfQ.eBdP5VG6RzZT1fzBm3NcYJiUomVol40UKhiddUjpuxjLOfl6xcNHS9XJ2Ni4sHpXKQjzSXY7HgwEsoBmPNF2-OVm7mLGn8VAddOCxkkDL7DwRrIfQX5q1TU7NYObQXow0MtlWgD8bDcxwp2nWd8cxlkKs3V5sNgCTsFi97lyVKFrwYav_z6otpF3hn9VAb0d5KR4nDK8Aszj1wW2kGXVQ6NAsVakYO30SV-DOE3kZMvjrgvek0vv0gZMjCi_5QcdWb5vgKxZ1aidkHCT6W6_CJv-K5_F9wlTIAsONNTT_XgApkP5m97XV7mYxPW0m7N2YJHksWb04DccHvGtCOS6NA"
}
###
POST http://localhost:4000/token 
#ada masalah dalam generate access token baru menggunakan refresh token.
#TypeError: Cannot read property 'name' of undefined
#saya sendiri juga bingung gimana konsep pengambilan namenya dari server lain.
Content-Type: application/json

{
    "token": "eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoibGFsYSIsImlhdCI6MTYzMjg5Mzg5MSwiZXhwIjoxNjMyODk0MTkxfQ.eBdP5VG6RzZT1fzBm3NcYJiUomVol40UKhiddUjpuxjLOfl6xcNHS9XJ2Ni4sHpXKQjzSXY7HgwEsoBmPNF2-OVm7mLGn8VAddOCxkkDL7DwRrIfQX5q1TU7NYObQXow0MtlWgD8bDcxwp2nWd8cxlkKs3V5sNgCTsFi97lyVKFrwYav_z6otpF3hn9VAb0d5KR4nDK8Aszj1wW2kGXVQ6NAsVakYO30SV-DOE3kZMvjrgvek0vv0gZMjCi_5QcdWb5vgKxZ1aidkHCT6W6_CJv-K5_F9wlTIAsONNTT_XgApkP5m97XV7mYxPW0m7N2YJHksWb04DccHvGtCOS6NA"
}

###
POST  http://localhost:4000/login 
Content-Type: application/json

{
    "username": "lala"
}
 
#jika terjadi masalah mungkin di server.js nya belum manggil dotenv